version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-py"
s3_prefix = "sam-hello-py"
region = "ap-northeast-3"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j9xk3zskqd3z"
